name: Java 21 CI with Maven

on:
  push:
    branches:
      - '*'  # Trigger on all branches
  pull_request:
    branches:
      - '*'  # Trigger on all branches

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Compile code
        run: mvn -B compile
        working-directory: ./lecture-scheduler

      - name: Run tests
        run: mvn -B test
        working-directory: ./lecture-scheduler
